/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author sapat
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        imagemDesc_lbl.setVisible(false);
        vamosNessa_btn.setVisible(false);
        pergunta1_lbl.setVisible(false);
        pergunta2_lbl.setVisible(false);
        resposta_cmb.setVisible(false);
        proximo_btn.setVisible(false);
        voltar_btn.setVisible(false);
        imagemFimQuiz_lbl.setVisible(false);
        imagemBaixoImpacto_lbl.setVisible(false);
        imagemImpactoModerado_lbl.setVisible(false);
        imagemAltoImpacto_lbl.setVisible(false);
        imagemAltissimoImpacto_lbl.setVisible(false);
        pegada_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sair_btn = new org.edisoncor.gui.button.ButtonAction();
        iniciar_btn = new org.edisoncor.gui.button.ButtonAqua();
        inicioQuiz_lbl = new javax.swing.JLabel();
        pressioneBotao_lbl = new javax.swing.JLabel();
        vamosNessa_btn = new org.edisoncor.gui.button.ButtonAqua();
        pergunta1_lbl = new javax.swing.JLabel();
        pergunta2_lbl = new javax.swing.JLabel();
        resposta_cmb = new javax.swing.JComboBox();
        proximo_btn = new org.edisoncor.gui.button.ButtonAqua();
        voltar_btn = new org.edisoncor.gui.button.ButtonAction();
        pegada_lbl = new javax.swing.JLabel();
        imagemAltissimoImpacto_lbl = new javax.swing.JLabel();
        imagemAltoImpacto_lbl = new javax.swing.JLabel();
        imagemImpactoModerado_lbl = new javax.swing.JLabel();
        imagemBaixoImpacto_lbl = new javax.swing.JLabel();
        imagemFimQuiz_lbl = new javax.swing.JLabel();
        imagemDesc_lbl = new javax.swing.JLabel();
        imagem_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        sair_btn.setText("SAIR");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(370, 450, 100, 30);

        iniciar_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        iniciar_btn.setText("INICIAR");
        iniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(iniciar_btn);
        iniciar_btn.setBounds(160, 210, 180, 70);

        inicioQuiz_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        inicioQuiz_lbl.setForeground(new java.awt.Color(255, 255, 255));
        inicioQuiz_lbl.setText("dar início ao quiz.");
        jPanel1.add(inicioQuiz_lbl);
        inicioQuiz_lbl.setBounds(20, 110, 490, 40);

        pressioneBotao_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        pressioneBotao_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pressioneBotao_lbl.setText("Pressione o botão para");
        jPanel1.add(pressioneBotao_lbl);
        pressioneBotao_lbl.setBounds(20, 80, 480, 40);

        vamosNessa_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        vamosNessa_btn.setText("VAMOS NESSA!");
        vamosNessa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vamosNessa_btnActionPerformed(evt);
            }
        });
        jPanel1.add(vamosNessa_btn);
        vamosNessa_btn.setBounds(320, 330, 150, 60);

        pergunta1_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        pergunta1_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pergunta1_lbl.setText("Qual é a quantidade de resíduos plásticos");
        jPanel1.add(pergunta1_lbl);
        pergunta1_lbl.setBounds(20, 110, 450, 40);

        pergunta2_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        pergunta2_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pergunta2_lbl.setText("gerada mensalmente pela empresa?");
        jPanel1.add(pergunta2_lbl);
        pergunta2_lbl.setBounds(20, 130, 460, 30);

        resposta_cmb.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        resposta_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menos de 100 kg", "Entre 100 kg e 500 kg", "Entre 500 kg e 1000 kg", "Mais de 1000 kg" }));
        resposta_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta_cmbActionPerformed(evt);
            }
        });
        jPanel1.add(resposta_cmb);
        resposta_cmb.setBounds(50, 180, 380, 40);

        proximo_btn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        proximo_btn.setText("Próximo");
        proximo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximo_btnActionPerformed(evt);
            }
        });
        jPanel1.add(proximo_btn);
        proximo_btn.setBounds(360, 350, 120, 60);

        voltar_btn.setText("VOLTAR");
        voltar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(voltar_btn);
        voltar_btn.setBounds(370, 420, 100, 30);

        pegada_lbl.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        pegada_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pegada_lbl.setText("40");
        jPanel1.add(pegada_lbl);
        pegada_lbl.setBounds(380, 260, 80, 80);

        imagemAltissimoImpacto_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/finalAltissimoImpacto.png"))); // NOI18N
        jPanel1.add(imagemAltissimoImpacto_lbl);
        imagemAltissimoImpacto_lbl.setBounds(-6, -6, 510, 510);

        imagemAltoImpacto_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/finalAltoImpacto.png"))); // NOI18N
        jPanel1.add(imagemAltoImpacto_lbl);
        imagemAltoImpacto_lbl.setBounds(-6, -6, 510, 510);

        imagemImpactoModerado_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/finalImpactoModerado.png"))); // NOI18N
        jPanel1.add(imagemImpactoModerado_lbl);
        imagemImpactoModerado_lbl.setBounds(-6, -6, 510, 510);

        imagemBaixoImpacto_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/finalBaixoImpacto.png"))); // NOI18N
        jPanel1.add(imagemBaixoImpacto_lbl);
        imagemBaixoImpacto_lbl.setBounds(-6, -6, 510, 510);

        imagemFimQuiz_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fimQuiz.png"))); // NOI18N
        jPanel1.add(imagemFimQuiz_lbl);
        imagemFimQuiz_lbl.setBounds(-6, -6, 510, 510);

        imagemDesc_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/descricao.png"))); // NOI18N
        jPanel1.add(imagemDesc_lbl);
        imagemDesc_lbl.setBounds(-6, -6, 510, 510);

        imagem_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        imagem_lbl.setText("jLabel1");
        jPanel1.add(imagem_lbl);
        imagem_lbl.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        Model.Funcoes_DAO.sair();
    }//GEN-LAST:event_sair_btnActionPerformed

    private void iniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_btnActionPerformed
        Model.Funcoes_DAO.iniciar();        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar_btnActionPerformed

    private void vamosNessa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vamosNessa_btnActionPerformed
        Model.Funcoes_DAO.vamosNessa();
    }//GEN-LAST:event_vamosNessa_btnActionPerformed

    private void proximo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximo_btnActionPerformed
        Model.Funcoes_DAO.proximo();
    }//GEN-LAST:event_proximo_btnActionPerformed

    private void resposta_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resposta_cmbActionPerformed

    private void voltar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_btnActionPerformed
        Model.Funcoes_DAO.voltar();
    }//GEN-LAST:event_voltar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel imagemAltissimoImpacto_lbl;
    public static javax.swing.JLabel imagemAltoImpacto_lbl;
    public static javax.swing.JLabel imagemBaixoImpacto_lbl;
    public static javax.swing.JLabel imagemDesc_lbl;
    public static javax.swing.JLabel imagemFimQuiz_lbl;
    public static javax.swing.JLabel imagemImpactoModerado_lbl;
    private javax.swing.JLabel imagem_lbl;
    public static org.edisoncor.gui.button.ButtonAqua iniciar_btn;
    public static javax.swing.JLabel inicioQuiz_lbl;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel pegada_lbl;
    public static javax.swing.JLabel pergunta1_lbl;
    public static javax.swing.JLabel pergunta2_lbl;
    public static javax.swing.JLabel pressioneBotao_lbl;
    public static org.edisoncor.gui.button.ButtonAqua proximo_btn;
    public static javax.swing.JComboBox resposta_cmb;
    private org.edisoncor.gui.button.ButtonAction sair_btn;
    public static org.edisoncor.gui.button.ButtonAqua vamosNessa_btn;
    public static org.edisoncor.gui.button.ButtonAction voltar_btn;
    // End of variables declaration//GEN-END:variables
}
